#pragma once
#define TRT_PHREG_ENABLE_BASEHAZ 0
#define TRT_PHREG_ENABLE_RESID   0
#define TRT_PHREG_ENABLE_ROBUST  0
#define TRT_PHREG_ENABLE_FIRTH   0
#define TRT_PHREG_ENABLE_PLCI    0
#define TRT_PHREG_ENABLE_REPN    0